covids/config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('staff/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
    path('cc/', include('close_contact.urls')),
    path('logs/', include('logs.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

covids/config/logs/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', LogListView.as_view(), name='logs_list'),
    path('new/', LogCreateView.as_view(), name='logs_new'),
    path('<int:pk>/', LogDetailView.as_view(), name='logs_detail'),
]

covids/config/logs/models.py
from django.db import models
from django.urls import reverse

from user.models import User
from staff.models import Staff

import datetime
# Create your models here.

class Log(models.Model):
    class CovidStatus(models.TextChoices):
        POSITIVE = 'P', ('Positive')
        NEGATIVE = 'N', ('Negative')

    class HealthStatus(models.TextChoices):
        SYMPTOMATIC = 'S', ('Symptomatic')
        ASYMPTOMATIC = 'A', ('Asymptomatic')

    covid_user_id = models.ForeignKey(User, on_delete=models.PROTECT)
    staff_id = models.ForeignKey(Staff, on_delete=models.PROTECT)

    date_swabbed = models.DateField()
    covid_status = models.TextField(choices=CovidStatus.choices, default=CovidStatus.NEGATIVE)

    date_recorded = models.DateField(auto_now_add=True)
    health_status = models.TextField(choices=HealthStatus.choices, default=HealthStatus.ASYMPTOMATIC)

    @property
    def date_quarantine_ends(self):
        return None if self.get_covid_status_display() == 'Negative' else self.date_swabbed + datetime.timedelta(days=14)

    def save(self, *args, **kwargs):
        user = User.objects.get(pk=self.covid_user_id.pk)
        user.quarantine_ends = self.date_quarantine_ends
        user.code = self.get_covid_status_display()
        self.covid_user_id = user
        user.save()
        super(Log, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.covid_user_id}-{self.date_swabbed}-{self.covid_status}-{self.health_status}'

    def get_absolute_url(self):
        return reverse('logs_detail', args=[str(self.id)])

covids/config/user/models.py
from django.db import models
from django.urls import reverse

from staff.models import Staff
# Create your models here.

class User(models.Model):
    class Sex(models.TextChoices):
        MAN = 'M', ('Man')
        WOMAN = 'F', ('Woman')

    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    birthdate = models.DateField()
    age = models.IntegerField()
    sex = models.CharField(max_length=1, choices=Sex.choices, null=True)
    profession = models.CharField(max_length=50)

    staff = models.ForeignKey(Staff, on_delete=models.PROTECT)

    code = models.CharField(max_length=8, null=True)
    quarantine_ends = models.DateField(null=True)

    def __str__(self):
        return f'{self.last_name}, {self.first_name} {self.middle_name}'

    def get_absolute_url(self):
        return reverse('user_detail', args=[str(self.id)])

covids/config/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Newspaper App{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}"><i class="fas fa-hospital-alt"></i> Covid System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              {% block navbar %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_list'%}">User List</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'logs_list'%}">Covid Logs List</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'cc_list'%}">Close Contact List</a>
                  </li>
              {% endblock%}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-secondary">Log In</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign Up</a>
            </form>
            {% endif %}
        </div>
    </nav>
    <main>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js">
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
</script>
<script src="https://unpkg.com/vue@next"></script>
<script type="text/javascript" src="https://kit.fontawesome.com/b5e97bb16b.js" crossorigin="anonymous"></script>

</html>

covids/config/templates/cc_detail.html
{% extends 'base.html' %}

{% block title %} Close Contact Detail {% endblock title %}

{% block content%}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>Recorded by {{ cc.staff_id }}</h3></span>
        </div>
        <div class="card-body">
            <p class="lead">Covid Close Contact: {{ cc.close_user_id }}</p>
            <p class="lead">Covid Carrier: {{ cc.covid_user_id }}</p>
            <p class="lead">Date Recorded: {{ cc.date_recorded }}</p>
            <p class="lead">Date Quarantine Ends (for Close Contact): {{ cc.date_quarantine_ends }}</p>
        </div>
    </div>
{% endblock content%}

covids/config/templates/cc_list.html
{% extends 'base.html' %}

{% block title %} Close Contact List {% endblock title %}

{% block navbar %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'user_list'%}">User List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'logs_list'%}">Covid Logs List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link active" href="{% url 'cc_list'%}">Close Contact List</a>
  </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <div class="d-inline-block">
          <a href="{% url 'cc_new' %}"><button class="btn btn-secondary">Create New Close Contact</button></a>
          <a href="{% url 'user_new' %}"><button class="btn btn-secondary">Create New User</button></a>
      </div>
      {% for cc in all_cc_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'cc_detail' cc.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ cc.close_user_id }} is a close contact of {{ cc.covid_user_id }}</h3></span>
                    <span class="text-muted">Recorded by: {{ cc.staff_id }}</span>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}

covids/config/templates/cc_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Close Contact Record {% endblock title %}

{% block content %}
    <div class="container-fluid mt-4">
        <h1>New Close Contact Record</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

covids/config/templates/home.html
{% extends 'base.html' %}

{% block title %}Covid System{% endblock title %}

{% block navbar %}
{% endblock %}

{% block content %}
<br />
<div class="jumbotron">
    <h1 class="display-4">Covid System App</h1>
    <p class="lead">A Covid system app for tracking covid positive patients and their close contacts.</p>
    {% if user.is_authenticated %}
        <hr class="my-2">
        <h2>Welcome, {{ user.username }}!</h2>
        <p class="lead">What do you want to do today?</p>
        <a href="{% url 'user_list' %}"><button class="btn btn-success">View User List</button></a>
        <a href="{% url 'logs_list' %}"><button class="btn btn-danger">View Covid Logs List</button></a>
        <a href="{% url 'cc_list' %}"><button class="btn btn-dark">View Close Contact List</button></a>
    {% endif %}
</div>
{% endblock content %}

covids/config/templates/logs_detail.html
{% extends 'base.html' %}

{% block title %} Close Contact Detail {% endblock title %}

{% block content%}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>{{ logs.covid_user_id }}</h3></span>
            <span class="text-muted">Recorded by: {{ logs.staff_id }}</span>
        </div>
        <div class="card-body">
            <p class="lead">Date Recorded: {{ logs.date_recorded }}</p>
            <p class="lead">Date Swabbed: {{ logs.date_swabbed }}</p>
            <p class="lead">Covid Status: {{ logs.get_covid_status_display }}</p>
            <p class="lead">Health Status: {{ logs.get_health_status_display }}</p>
        </div>
        <div class="card-footer">
            <p class="lead">Date Quarantine Ends: {{ logs.date_quarantine_ends }}</p>
        </div>
    </div>
{% endblock content%}

covids/config/templates/logs_list.html
{% extends 'base.html' %}

{% block title %} Covid Logs List {% endblock title %}

{% block navbar %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'user_list'%}">User List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link active" href="{% url 'logs_list'%}">Covid Logs List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'cc_list'%}">Close Contact List</a>
  </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <div class="d-inline-block">
          <a href="{% url 'logs_new' %}"><button class="btn btn-secondary">Create New Covid Logs</button></a>
          <a href="{% url 'user_new' %}"><button class="btn btn-secondary">Create New User</button></a>
      </div>
      {% for log in all_logs_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'logs_detail' log.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ log.covid_user_id }}</h3></span>
                    <span class="text-muted">Recorded by: {{ log.staff_id }}</span>
                </div>
                <div class="card-body">
                    <p class="lead">Covid Status: {{ log.get_covid_status_display }}</p>
                    <p class="lead">Health Status: {{ log.get_health_status_display }}</p>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}

covids/config/templates/logs_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Covid Log {% endblock title %}

{% block content %}
    <div class="container-fluid mt-4">
        <h1>New Covid Log</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

covids/config/templates/user_detail.html
{% extends 'base.html' %}

{% block title %} User List {% endblock title %}

{% block content%}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>{{ d_user.last_name }}, {{ d_user.first_name}} {{ d_user.middle_name}}</h3></span>
            <span class="text-muted">Recorded by {{ d_user.staff }}</span>
        </div>
        <div class="card-body">
            <p class="lead">Covid Reference ID: {{ d_user.pk }}</p>
            <p class="lead">Age: {{ d_user.age }}</p>
            <p class="lead">Sex: {{ d_user.get_sex_display }}</p>
            <p class="lead">Profession: {{ d_user.profession }}</p>
            <p class="lead">Code: {{ d_user.code }}</p>
            <p class="lead">Date Quarantine Ends: {{ d_user.quarantine_ends }}</p>
        </div>
        <div class="card-footer">
            <a href="{% url 'user_edit' d_user.pk %}">Edit</a>
        </div>
    </div>
{% endblock content%}

covids/config/templates/user_list.html
{% extends 'base.html' %}

{% block title %} User List {% endblock title %}

{% block navbar %}
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'user_list'%}">User List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'logs_list'%}">Covid Logs List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'cc_list'%}">Close Contact List</a>
  </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <a href="{% url 'user_new' %}"><button class="btn btn-secondary">Create New User</button></a>
      {% for user in all_user_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'user_detail' user.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ user.last_name }}, {{ user.first_name}} {{ user.middle_name}}</h3></span>
                    <span class="text-muted">Recorded by {{ user.staff }}</span>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}