church/config/church/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', AttendanceListView.as_view(), name='attend_list'),
    path('new/', AttendanceCreateView.as_view(), name='attend_new'),
    path('<int:pk>/', AttendanceDetailView.as_view(), name='attend_detail'),
]

church/config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')), # new
    path('staff/', include('django.contrib.auth.urls')), # new
    path('user/', include('user.urls')),
    path('ref/', include('reference.urls')),
    path('attendance/', include('church.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

church/config/reference/api/urls.py
from django.urls import path

from ..views import CovidReferenceUpdateModelView, CovidReferenceListModelView

urlpatterns = [
    path('', CovidReferenceListModelView.as_view()),
    path('<int:pk>', CovidReferenceUpdateModelView.as_view())
]

church/config/reference/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', CovidReferenceListView.as_view(), name='ref_list'),
    path('new/', CovidReferenceCreateView.as_view(), name='ref_new'),
    path('<int:pk>/', CovidReferenceDetailView.as_view(), name='ref_detail'),
    path('api/', include('reference.api.urls'))
]

church/config/user/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('new/', UserCreateView.as_view(), name='user_new'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
]

church/config/church/models.py
from django.db import models
from django.urls import reverse

from staff.models import Staff
from user.models import User
# Create your models here.

class Attendance(models.Model):
    class Event(models.TextChoices):
        MASS = 'MA', ('Mass')
        BAPTISM = 'B', ('Baptism')
        MARRIAGE = 'MAR', ('Marriage')
        FUNERAL = 'F', ('Funeral')
        OTHERS = 'O', ('Others')

    user_id = models.ForeignKey(User, on_delete=models.PROTECT) # => call
    date_attended = models.DateField(auto_now_add=True)

    event_type = models.CharField(max_length=3, choices=Event.choices, default=Event.MASS)
    staff_id = models.ForeignKey(Staff, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.event_type}-{self.date_attended}-{self.user_id}'

    def get_absolute_url(self):
        return reverse('attend_detail', args=[str(self.id)])

church/config/reference/models.py
from django.db import models
from django.urls import reverse

from user.models import User
from staff.models import Staff
# Create your models here.

class CovidReference(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    staff_id = models.ForeignKey(Staff, on_delete=models.PROTECT)
    covid_reference_id = models.CharField(max_length=6)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.covid_reference_id

    def get_absolute_url(self):
        return reverse('ref_detail', args=[str(self.user_id)])

church/config/staff/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Staff(AbstractUser):
    class Sex(models.TextChoices):
        MAN = 'M', ('Man')
        WOMAN = 'F', ('Woman')
    sex = models.CharField('sex', max_length=1, choices=Sex.choices, null=True)

    def __str__(self):
        return f'{self.username}'

church/config/user/models.py
from django.db import models
from django.urls import reverse
from staff.models import Staff
# Create your models here.

class User(models.Model):
    class Sex(models.TextChoices):
        MAN = 'M', ('Man')
        WOMAN = 'F', ('Woman')
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    birthdate = models.DateField()
    age = models.IntegerField()
    sex = models.CharField(max_length=1, choices=Sex.choices, null=True)
    profession = models.CharField(max_length=50)

    staff = models.ForeignKey(Staff, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.last_name}, {self.first_name} {self.middle_name[0]}.'

    def get_absolute_url(self):
        return reverse('user_detail', args=[str(self.id)])

church/config/staff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Staff

class StaffCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Staff
        fields = UserCreationForm.Meta.fields + ('email', 'sex',)

class StaffChangeForm(UserChangeForm):
    class Meta:
        model = Staff
        fields = UserChangeForm.Meta.fields

church/config/church/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from .models import Attendance
# Create your views here.

class AttendanceListView(LoginRequiredMixin, ListView):
    model = Attendance
    template_name = 'attend_list.html'
    context_object_name = 'all_attends_list'

class AttendanceCreateView(LoginRequiredMixin, CreateView):
    model = Attendance
    template_name = 'attend_new.html'
    fields = ('user_id', 'event_type', 'staff_id')

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)

class AttendanceDetailView(LoginRequiredMixin, DetailView):
    model = Attendance
    template_name = 'attend_detail.html'
    context_object_name = 'attend'

church/config/reference/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from rest_framework.generics import RetrieveUpdateAPIView, ListAPIView

from .serializers import CovidReferenceUpdateModelSerializer
from .models import CovidReference
# Create your views here.

# API views

class CovidReferenceUpdateModelView(RetrieveUpdateAPIView):
    queryset = CovidReference.objects.all()
    serializer_class = CovidReferenceUpdateModelSerializer

class CovidReferenceListModelView(ListAPIView):
    queryset = CovidReference.objects.all()
    serializer_class = CovidReferenceUpdateModelSerializer

# Default views

class CovidReferenceListView(LoginRequiredMixin, ListView):
    model = CovidReference
    template_name = 'ref_list.html'
    context_object_name = 'all_refs_list'

class CovidReferenceCreateView(LoginRequiredMixin, CreateView):
    model = CovidReference
    template_name = 'ref_new.html'
    fields = ('user', 'staff_id', 'covid_reference_id')

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)

class CovidReferenceDetailView(LoginRequiredMixin, DetailView):
    model = CovidReference
    template_name = 'ref_detail.html'
    context_object_name = 'ref'

church/config/user/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (
    UpdateView, CreateView
)

from .models import User
# Create your views here.

class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'user_list.html'
    context_object_name = 'all_user_list'

class UserCreateView(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'user_new.html'
    fields = ('first_name', 'middle_name', 'last_name', 'birthdate', 'age', 'sex', 'profession', 'staff')

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'd_user'

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('first_name', 'middle_name', 'last_name', 'birthdate', 'age', 'sex', 'profession', 'staff')
    template_name = 'user_edit.html'

church/config/templates/attend_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} User List {% endblock title %}

{% block script %}
    <script type="text/javascript">
        firstName = "{{ attend.user_id.first_name }}";
        refID = "{{ attend.user_id.id }}";
    </script>
{% endblock %}

{% block content%}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>{{ attend.user_id }}</h3></span>
            <span class="text-muted">Recorded by {{ attend.staff_id }}</span>
        </div>
        <div class="card-body">
            <p class="lead">Event: {{ attend.get_event_type_display }}</p>
            <p class="lead">Date Attended: {{ attend.date_attended }}</p>
            <span id="covid_ref">
                <p class="lead">[[ code ]]</p>
                <p class="lead">[[ date_quarantine_ends ]]</p>
            </span>
        </div>
    </div>
    <div class="form-group mt-4">
        <a href="{% url 'attend_new' %}"><button class="btn btn-primary">Add New Attendance</button></a>
    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js">
        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
    </script>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="{% static 'js/user.js' %}" charset="utf-8"></script>
{% endblock %}

church/config/templates/attend_list.html
{% extends 'base.html' %}

{% block title %} User List {% endblock title %}

{% block navbar %}
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'attend_list'%}">Attendance List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'ref_list'%}">Covid Reference List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'user_list'%}">User List</a>
  </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <a href="{% url 'attend_new' %}"><button class="btn btn-secondary">Add New Attendance Record</button></a>
      {% for attend in all_attends_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'attend_detail' attend.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ attend.user_id }} attended {{ attend.get_event_type_display }} on {{ attend.date_attended}}</h3></span>
                    <span class="text-muted">Recorded by {{ attend.staff_id }}</span>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}

church/config/templates/attend_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Attendance {% endblock title %}

{% block content %}
    <div class="container-fluid mt-4">
        <h1>New Attendance</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

church/config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Church System App{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% block script %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}"><i class="fas fa-church"></i> Church System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              {% block navbar %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'attend_list'%}">Attendance List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ref_list' %}">Covid Reference List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_list'%}">User List</a>
                </li>
              {% endblock%}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-secondary">Log In</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign Up</a>
            </form>
            {% endif %}
        </div>
    </nav>
    <main>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://kit.fontawesome.com/b5e97bb16b.js" crossorigin="anonymous"></script>

</html>

church/config/templates/home.html
{% extends 'base.html' %}

{% block title %}Church System{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
<br />
<div class="jumbotron">
    <h1 class="display-4">Church System App</h1>
    <p class="lead">A Church system app for tracking all members of the church.</p>
    {% if user.is_authenticated %}
        <hr class="my-2">
        <h2>Welcome, {{ user.username }}!</h2>
        <p class="lead">What do you want to do today?</p>
        <a href="{% url 'attend_list' %}"><button class="btn btn-danger">View Attendance List</button></a>
        <a href="{% url 'ref_list' %}"><button class="btn btn-dark">View Covid Reference List</button></a>
        <a href="{% url 'user_list' %}"><button class="btn btn-success">View User List</button></a>
    {% endif %}
</div>
{% endblock content %}

church/config/templates/ref_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Covid Reference Detail {% endblock title %}

{% block script %}
    <script type="text/javascript">
        firstName = "{{ ref.user.first_name }}";
        middleName =  "{{ ref.user.middle_name }}";
        lastName = "{{ ref.user.last_name }}";
        covidID = "{{ ref.covid_reference_id }}";
        currentID = "{{ ref.user_id }}";
        csrftoken = "{{ csrf_token }}";
    </script>
{% endblock %}

{% block content %}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>{{ ref.user }}</h3></span>
        </div>
        <div class="card-body">
            <p class="lead">Covid Reference ID: {{ ref.covid_reference_id }}</p>
            <p class="lead">Recorded by: {{ ref.staff_id }}</p>
            <p class="lead">Verified: <span class="badge badge-pill badge-secondary">{{ ref.verified }}</span></p>
        </div>
        {% if not ref.verified %}
        <div class="card-footer d-inline-block" id="app">
            <button class="btn btn-primary" @click="verifyCovidReference">Verify</button>
            [[ message ]]
        </div>
        {% endif %}
    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="{% static 'js/app.js' %}" charset="utf-8"></script>
{% endblock content %}

church/config/templates/ref_list.html
{% extends 'base.html' %}

{% block title %} Covid Reference List {% endblock title %}

{% block navbar %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'attend_list'%}">Attendance List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link active" href="{% url 'ref_list' %}">Covid Reference List</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'user_list'%}">User List</a>
  </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <a href="{% url 'ref_new' %}"><button class="btn btn-secondary">Create New Covid Reference</button></a>
      {% for ref in all_refs_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'ref_detail' ref.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ ref.user }}</h3></span>
                    <span class="text-muted">Recorded by {{ ref.staff_id }}</span>
                </div>
                <div class="card-body">
                    <p class="lead">Reference ID: {{ ref.covid_reference_id }}</p>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}

church/config/templates/ref_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New Covid Reference {% endblock title %}

{% block content %}
    <div class="container-fluid mt-4">
        <h1>New Covid Reference</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

church/config/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} User Detail {% endblock title %}

{% block script %}
    <script type="text/javascript">
        refID = "{{ d_user.pk }}";
        firstName = "{{ d_user.first_name }}";
    </script>
{% endblock %}

{% block content %}
    <div class="card mt-4">
        <div class="card-header">
            <span class="font-weight-bold d-block"><h3>{{ d_user.last_name }}, {{ d_user.first_name }} {{ d_user.middle_name }}</h3></span>
            <span class="text-muted">Recorded by {{ d_user.staff }}</span>
        </div>
        <div class="card-body">
            <p class="lead">Age: {{ d_user.age }}</p>
            <p class="lead">Sex: {{ d_user.get_sex_display }}</p>
            <p class="lead">Profession: {{ d_user.profession }}</p>
            <span id="covid_ref">
                <p class="lead">[[ code ]]</p>
                <p class="lead">[[ date_quarantine_ends ]]</p>
            </span>
        </div>
        <div class="card-footer">
            <a href="{% url 'user_edit' d_user.pk %}">Edit</a>
        </div>
    </div>
    <script src="https://unpkg.com/axios/dist/axios.min.js">
        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
    </script>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="{% static 'js/user.js' %}" charset="utf-8"></script>
{% endblock content%}

church/config/templates/user_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit User {% endblock title %}

{% block navbar %}

{% endblock %}

{% block content %}
    <div class="container">
        <h1>Edit User</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
            <h3>Note: Date format is YYYY-MM-DD</h3>
        </form>
    </div>
{% endblock content %}

church/config/templates/user_list.html
{% extends 'base.html' %}

{% block title %} User List {% endblock title %}

{% block navbar %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'attend_list'%}">Attendance List</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'ref_list' %}">Covid Reference List</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'user_list'%}">User List</a>
    </li>
{% endblock%}

{% block content%}
  <div class="container-fluid mt-4">
      <a href="{% url 'user_new' %}"><button class="btn btn-secondary">Create New User</button></a>
      {% for user in all_user_list %}
        <div class="card mt-4">
            <a style="text-decoration: none;" href="{% url 'user_detail' user.pk %}">
                <div class="card-header">
                    <span class="font-weight-bold d-block"><h3>{{ user.last_name }}, {{ user.first_name}} {{ user.middle_name}}</h3></span>
                    <span class="text-muted">Recorded by {{ user.staff }}</span>
                </div>
            </a>
        </div>
      {% endfor %}
  </div>
{% endblock content%}

church/config/templates/user_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} New User {% endblock title %}

{% block content %}
    <div class="container-fluid mt-4">
        <h1>New User</h1>
        <form action="" method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </div>
            <h3>Note: Date format is YYYY-MM-DD</h3>
        </form>
    </div>
{% endblock content %}